<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<div class="pdfheader-print-product">
<?php if (Mage::getStoreConfig('pdffree/options/enable_preview')): ?>
    <a target="_blank" class="print-product" href="<?php echo $this->getUrl('pdffree/product/view/').'id/'.$_product->getId(); ?>/"> 
        <img title="preview PDF" src="<?php echo $this->getSkinUrl('ip_pdffree/images/pdf_view.png'); ?>"/>
    </a> 
    <?php endif;?>
    <?php if (Mage::getStoreConfig('pdffree/options/enable_stream')): ?>
    <a class="print-product" href="<?php echo $this->getUrl('pdffree/product/print/').'id/'.$_product->getId(); ?>/"> 
        <img title="print PDF" src="<?php echo $this->getSkinUrl('ip_pdffree/images/pdf_download.png'); ?>"/>
    </a> 
    <?php endif;?>
    <?php if (Mage::getStoreConfig('pdffree/options/enable_save')): ?>
    <a class="print-product" href="<?php echo $this->getUrl('pdffree/product/save/').'id/'.$_product->getId(); ?>/"> 
        <img title="save PDF" src="<?php echo $this->getSkinUrl('ip_pdffree/images/pdf_save.png'); ?>"/>
    </a> 
    <?php endif;?>

</div>

