<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $categoryId = (int) $this->getRequest()->getParam('id', false);
    $_category = Mage::getModel('catalog/category')->load($categoryId);
?>

<h2 class="pdf-category-header"> 
    <?php echo $_category->getName(); ?>
</h2>


<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

            <div class="category-products">
                <?php $_iterator = 0; ?>
                <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                        <table width="100%" cellpadding="3" cellspacing="3">
                            <tr>

                                <td width="150px">
                                    <div class="product-img-box">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                                    </div>                            
                                </td>

                                <td>
                                    <div class="product-shop">
                                        <div class="f-fix">
                                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                            <?php if($_product->getRatingSummary()): ?>
                                            <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                            <?php endif; ?>
                                            <?php echo $this->getPriceHtml($_product, true) ?>
                                            <div class="desc std">
                                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                            </div>
                                        </div>
                                    </div>
                            
                                    </td>
                                </tr>
                        </table>                                       
                    </li>
                <?php endforeach; ?>
                </ol>
                <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
            </div>



<?php endif; ?>
