<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    
    <?php $file = Mage::getStoreConfig('pdffree/options/css'); ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('ip_pdffree/css/'.$file); ?>" media="all" />
    
</head>
<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <div class="wrapper">
        <div class="page">
            <div class="main-container col1-layout">
                <div class="main">
                    <div class="col-main">
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
